// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8IepaOrAH1tRsNkvLTN9VbgI1OaYgNnc',
    appId: '1:524590457409:web:e386669826699d12185cc0',
    messagingSenderId: '524590457409',
    projectId: 'new-app-c297d',
    authDomain: 'new-app-c297d.firebaseapp.com',
    storageBucket: 'new-app-c297d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlNRpsdrWltZ5LoKEihASfhlFwiRXQy80',
    appId: '1:524590457409:android:98ac3dbe30b77e1a185cc0',
    messagingSenderId: '524590457409',
    projectId: 'new-app-c297d',
    storageBucket: 'new-app-c297d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClCN_ZpsmXMOnmlY4rmtXw9oh8iTMn314',
    appId: '1:524590457409:ios:42da12dd5e9dbbff185cc0',
    messagingSenderId: '524590457409',
    projectId: 'new-app-c297d',
    storageBucket: 'new-app-c297d.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClCN_ZpsmXMOnmlY4rmtXw9oh8iTMn314',
    appId: '1:524590457409:ios:42da12dd5e9dbbff185cc0',
    messagingSenderId: '524590457409',
    projectId: 'new-app-c297d',
    storageBucket: 'new-app-c297d.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8IepaOrAH1tRsNkvLTN9VbgI1OaYgNnc',
    appId: '1:524590457409:web:b97071ab3340dde5185cc0',
    messagingSenderId: '524590457409',
    projectId: 'new-app-c297d',
    authDomain: 'new-app-c297d.firebaseapp.com',
    storageBucket: 'new-app-c297d.firebasestorage.app',
  );
}
